services:
  db:
    image: postgres:15-alpine
    container_name: form-db
    environment:
      POSTGRES_USER: formuser
      POSTGRES_PASSWORD: formpass
      POSTGRES_DB: formsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: form-backend
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      DB_HOST: db   # задаём явно, чтобы контейнер подключался к сервису db
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
