name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build backend binary
        run: |
          cd backend
          CGO_ENABLED=0 go build -o hello main.go

      - name: Copy binary to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend/hello"
          target: "/root/form-builder/backend/"
          strip_components: 1   # убирает папку backend/ из пути, чтобы файл попал прямо в target

      - name: Restart containers on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/form-builder
            docker compose down
            docker compose up -d --build
